### ISSUE TITLE
Significant CPU usage noticed

### ISSUE THREAD

**Issue by da-wolff** [tim-hellhake/systeminfo-adapter#18] opened 2020-07-30 03:50 UTC
Hi, great app thanks, however I notice that is results in reasonably high, sustained, CPU usage.  To be honest any add-ons that are not produced by mozilla I seem to have a similar issue.  
I am running WebThings on a Raspberry Pi 4B inside a Docker container, if that helps at all.

**Comment by tim-hellhake** [comment] 2020-07-30 21:20
Thanks for the feedback @da-wolff.

> I notice that is results in reasonably high, sustained, CPU usage

Do you mean the overall utilization, or did you monitor the CPU usage of a single addon process?
Which command did you use to measure the CPU usage?

**Comment by da-wolff** [comment] 2020-08-03 02:23
@tim-hellhake it is definitely a single process that generates the high CPU usage and temperature.  I have used multiple monitoring methods to identify the item.  

Simply using "Top" & hitting 'c' to show the full process name it shows a constant ~20% CPU for this one process:  "node /home/node/mozilla-iot/gateway/src/addon-loader.js /home/node/.mozilla-iot/addons/systeminfo-adapter "

![System Info Top](https://user-images.githubusercontent.com/68982071/89140066-e5241280-d583-11ea-8f1c-729a95848c13.PNG)

The built in Task Manager also shows this process as the highest when sorting by CPU usage.

I also use the "RPi-Monitor" application on the raspberry pi and that shows the temperature and the CPU usage constantly trending up with this add-on enabled.  When I disable it everything goes back to very low usage.
Let me know if you require any more information to assist.

Cheers.

**Comment by flatsiedatsie** [comment] 2020-08-04 09:07
Perhaps there could be a setting to set polling frequency? This would also help keep logs from filling up with too much detail if a user doesn't care about the second to second values that much.

**Comment by da-wolff** [comment] 2020-08-04 12:16
Sounds like a great idea! That would work well for me.

**Comment by tim-hellhake** [comment] 2020-08-04 22:10
I added a config option for the polling interval.
As soon as the PR is merged you can install the new update.
Please let me know if this solves the problem.

**Comment by da-wolff** [comment] 2020-08-05 12:30
Hi all, I have tested this update and it does not reduce the CPU utilisation.  I pushed the polling period out to 30 seconds however the task itself consistently maintained around 30% CPU usage as it did before and didn't let up.  

I did however look at the logs this time and found this ERROR being repeated for each property request.  Not sure if this has any significance here or if it just ignores this and carries on?  Either way it doesn't appear to be going to sleep in the 'quiet times' between polls somehow.

"2020-08-05 22:12:49.462 ERROR  : Plugin: systeminfo-adapter Unrecognized adapter: SysteminfoAdapter Ignoring msg: "

Please let me know if you would like any more diagnostics to assist.

**Comment by tim-hellhake** [comment] 2020-08-05 17:59
> Hi all, I have tested this update and it does not reduce the CPU utilisation.

Ok, that's strange.
I'll try to replicate it locally.

> I did however look at the logs this time and found this ERROR being repeated for each property request.

In which interval do the messages appear? 30s?

> "2020-08-05 22:12:49.462 ERROR : Plugin: systeminfo-adapter Unrecognized adapter: SysteminfoAdapter Ignoring msg: "

Can you attach the rest of the message?
There should be also a message number.

**Comment by tim-hellhake** [comment] 2020-08-05 20:22
I think i found the issue.
One of the methods expects milliseconds instead of seconds.
The next update should fix it.

**Comment by da-wolff** [comment] 2020-08-05 23:13
@tim-hellhake  I can confirm that data updates are happening at the interval specified but something must still be active on a very regular basis.  That is great that you found a timer base was incorrect and certainly sounds like it could cause issues if a timer was specified thinking it was seconds when it was milliseconds!  Great, I look forward to the update.

FYI i captured more of the error I was talking about & it looks to just be when I disable the add-on and it unloads from the system.  Maybe this is normal, but either way shouldn't really pose a problem.

----------------------------------------------------------------------------------
2020-08-06 09:05:26.315 INFO   : Loading add-on: systeminfo-adapter
2020-08-06 09:05:27.223 INFO   : systeminfo-adapter: Opening database: /home/node/.mozilla-iot/config/db.sqlite3
2020-08-06 09:05:27.575 INFO   : systeminfo-adapter: Loading add-on systeminfo-adapter from /home/node/.mozilla-iot/addons/systeminfo-adapter
2020-08-06 09:05:29.357 WARN   : Rule property unable to get initial value: Did not get a real value
2020-08-06 09:05:29.372 INFO   : systeminfo-adapter: Next unit is d
2020-08-06 09:05:29.438 INFO   : getValue for property uptime for: System returning 88087
2020-08-06 09:05:29.439 INFO   : getValue for property scaledUptime for: System returning 1.0195254629629629
2020-08-06 09:05:29.868 INFO   : systeminfo-adapter: Creating network for lo
2020-08-06 09:05:29.872 INFO   : systeminfo-adapter: Creating network for eth0
2020-08-06 09:05:29.875 INFO   : systeminfo-adapter: Creating network for docker0
2020-08-06 09:05:29.877 INFO   : systeminfo-adapter: Creating network for veth3566699
2020-08-06 09:05:29.943 INFO   : systeminfo-adapter: Creating disk for /etc/hosts
2020-08-06 09:06:28.446 INFO   : Unloading SysteminfoAdapter
2020-08-06 09:06:28.749 INFO   : systeminfo-adapter: Adapter: SysteminfoAdapter unloaded
2020-08-06 09:06:28.752 ERROR  : Plugin: systeminfo-adapter Unrecognized adapter: SysteminfoAdapter Ignoring msg: {
  messageType: 8199,
  data: {
    adapterId: 'SysteminfoAdapter',
    deviceId: '/etc/hosts',
    property: {
      name: 'memAvailable',
      value: 14.986862182617188,
      visible: true,
      title: 'Available memory',
      type: 'number',
      '@type': 'LevelProperty',
      unit: 'GB',
      description: 'Available memory',
      minimum: 0,
      maximum: 27.338008880615234,
      readOnly: true
    },
    pluginId: 'systeminfo-adapter'
  }
}
2020-08-06 09:06:28.754 ERROR  : Plugin: systeminfo-adapter Unrecognized adapter: SysteminfoAdapter Ignoring msg: {
  messageType: 8199,
  data: {
    adapterId: 'SysteminfoAdapter',
    deviceId: 'eth0',
    property: {
      name: 'currentRxSpeed',
      value: 0.043248837710889575,
      visible: true,
      title: 'RX speed',
      type: 'number',
      unit: 'MBit/s',
      minimum: 0,
      maximum: 1000,
      readOnly: true
    },
    pluginId: 'systeminfo-adapter'
  }
}
2020-08-06 09:06:28.755 ERROR  : Plugin: systeminfo-adapter Unrecognized adapter: SysteminfoAdapter Ignoring msg: {
  messageType: 8199,
  data: {
    adapterId: 'SysteminfoAdapter',
    deviceId: 'eth0',
    property: {
      name: 'currentTxSpeed',
      value: 0.040534083828604295,
      visible: true,
      title: 'TX speed',
      type: 'number',
      unit: 'MBit/s',
      minimum: 0,
      maximum: 1000,
      readOnly: true
    },
    pluginId: 'systeminfo-adapter'
  }
}
2020-08-06 09:06:28.756 ERROR  : Plugin: systeminfo-adapter Unrecognized adapter: SysteminfoAdapter Ignoring msg: {
  messageType: 8199,
  data: {
    adapterId: 'SysteminfoAdapter',
    deviceId: 'eth0',
    property: {
      name: 'currentSpeed',
      value: 0.08378292153949388,
      visible: true,
      title: 'Total speed',
      type: 'number',
      '@type': 'LevelProperty',
      unit: 'MBit/s',
      minimum: 0,
      maximum: 1000,
      readOnly: true
    },
    pluginId: 'systeminfo-adapter'
  }
}

**Comment by da-wolff** [comment] 2020-08-06 03:00
Version 1.9.0 looks to be working great now.  The system is settled and no more excessive CPU activity.
Good find!
Thanks.

**Comment by flatsiedatsie** [comment] 2020-08-06 14:44
Very happy with the polling frequency option too :-)

**Comment by tim-hellhake** [comment] 2020-08-06 22:29
@da-wolff I'm glad that the issue is resolved now.
@flatsiedatsie Nice to hear that!

**Closed by tim-hellhake** 2020-08-06 22:29 UTC
